version: '3.9'

services:
  openclaw:
    image: openclaw/openclaw:latest
    container_name: openclaw
    restart: unless-stopped
    ports:
      - "19000:19000"
    volumes:
      - ./openclaw/data:/data
      - ./openclaw/config:/config
    environment:
      - OPENAI_API_KEY=your_openai_key_here
      - ANTHROPIC_API_KEY=your_anthropic_key_here

networks:
  default:
    name: agent-network
